# Generated by Django 5.1.6 on 2025-02-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='total_price_at_purchase',
        ),
    ]
