# Generated by Django 5.1.6 on 2025-02-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_total_price_orderitem_total_price_at_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
