# Generated by Django 5.1.6 on 2025-02-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_price_at_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
